language: python

python:
  - "2.7"
  - "2.6"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7

install:
  - pip install tox>=1.8

script: tox -e django-${DJANGO_VERSION},pep8